<!-- Email Body : BEGIN -->
<table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="600" style="margin: auto;" class="email-container">

    <!-- Hero Image, Flush : BEGIN -->
    <tr>
        <td bgcolor="#ffffff">
            <img src="http://placehold.it/1200x600" aria-hidden="true" width="600" height="" alt="alt_text" border="0" align="center" style="width: 100%; max-width: 600px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;" class="g-img">
        </td>
    </tr>
    <!-- Hero Image, Flush : END -->

    <!-- 1 Column Text + Button : BEGIN -->
    <tr>
        <td bgcolor="#ffffff" style="padding: 40px; text-align: center; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
            Maecenas sed ante pellentesque, posuere leo id, eleifend dolor.
            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
            Praesent laoreet malesuada cursus. Maecenas scelerisque congue eros eu posuere.
            Praesent in felis ut velit pretium lobortis rhoncus ut&nbsp;erat.
            <?php echo $this->sampleTemplateData; ?>
            <br><br>
            <!-- Button : BEGIN -->
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto">
                <tr>
                    <td style="border-radius: 3px; background: #222222; text-align: center;" class="button-td">
                        <a href="http://www.google.com" style="background: #222222; border: 15px solid #222222; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
                            &nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#ffffff;">A Button</span>&nbsp;&nbsp;&nbsp;&nbsp;
                        </a>
                    </td>
                </tr>
            </table>
            <!-- Button : END -->
        </td>
    </tr>
    <!-- 1 Column Text + Button : END -->

    <!-- Background Image with Text : BEGIN -->
    <tr>
        <!-- Bulletproof Background Images c/o https://backgrounds.cm -->
        <td background="http://placehold.it/600x230/222222/666666" bgcolor="#222222" valign="middle" style="text-align: center; background-position: center center !important; background-size: cover !important;">

            <!--[if gte mso 9]>
            <v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="width:600px;height:175px; background-position: center center !important;">
                <v:fill type="tile" src="http://placehold.it/600x230/222222/666666" color="#222222" />
                <v:textbox inset="0,0,0,0">
            <![endif]-->
            <div>
                <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td valign="middle" style="text-align: center; padding: 40px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #ffffff;">
                            Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent laoreet malesuada cursus. Maecenas scelerisque congue eros eu posuere. Praesent in felis ut velit pretium lobortis rhoncus ut&nbsp;erat.
                        </td>
                    </tr>
                </table>
            </div>
            <!--[if gte mso 9]>
            </v:textbox>
            </v:rect>
            <![endif]-->
        </td>
    </tr>
    <!-- Background Image with Text : END -->

    <!-- 2 Even Columns : BEGIN -->
    <tr>
        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 10px;">
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                    <!-- Column : BEGIN -->
                    <td class="stack-column-center">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td style="padding: 10px; text-align: center">
                                    <img src="http://placehold.it/270" aria-hidden="true" width="270" height="270" alt="alt_text" border="0" class="fluid" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                            <tr>
                                <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0 10px 10px; text-align: left;" class="center-on-narrow">
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                    <!-- Column : BEGIN -->
                    <td class="stack-column-center">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td style="padding: 10px; text-align: center">
                                    <img src="http://placehold.it/270" aria-hidden="true" width="270" height="270" alt="alt_text" border="0" class="fluid" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                            <tr>
                                <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0 10px 10px; text-align: left;" class="center-on-narrow">
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                </tr>
            </table>
        </td>
    </tr>
    <!-- 2 Even Columns : END -->

    <!-- 3 Even Columns : BEGIN -->
    <tr>
        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 10px;">
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                    <!-- Column : BEGIN -->
                    <td width="33.33%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td style="padding: 10px; text-align: center">
                                    <img src="http://placehold.it/170" aria-hidden="true" width="170" height="170" alt="alt_text" border="0" class="fluid" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                            <tr>
                                <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0 10px 10px; text-align: left;" class="center-on-narrow">
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                    <!-- Column : BEGIN -->
                    <td width="33.33%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td style="padding: 10px; text-align: center">
                                    <img src="http://placehold.it/170" aria-hidden="true" width="170" height="170" alt="alt_text" border="0" class="fluid" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                            <tr>
                                <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0 10px 10px; text-align: left;" class="center-on-narrow">
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                    <!-- Column : BEGIN -->
                    <td width="33.33%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td style="padding: 10px; text-align: center">
                                    <img src="http://placehold.it/170" aria-hidden="true" width="170" height="170" alt="alt_text" border="0" class="fluid" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                            <tr>
                                <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 0 10px 10px; text-align: left;" class="center-on-narrow">
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                </tr>
            </table>
        </td>
    </tr>
    <!-- 3 Even Columns : END -->

    <!-- Thumbnail Left, Text Right : BEGIN -->
    <tr>
        <td bgcolor="#ffffff" dir="ltr" align="center" valign="top" width="100%" style="padding: 10px;">
            <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <!-- Column : BEGIN -->
                    <td width="33.33%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td dir="ltr" valign="top" style="padding: 0 10px;">
                                    <img src="http://placehold.it/170" aria-hidden="true" width="170" height="170" alt="alt_text" border="0" class="center-on-narrow" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                    <!-- Column : BEGIN -->
                    <td width="66.66%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td dir="ltr" valign="top" style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 10px; text-align: left;" class="center-on-narrow">
                                    <strong style="color:#111111;">Class aptent taciti sociosqu</strong>
                                    <br><br>
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                    <br><br>
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" class="center-on-narrow" style="float:left;">
                                        <tr>
                                            <td style="border-radius: 3px; background: #222222; text-align: center;" class="button-td">
                                                <a href="http://www.google.com" style="background: #222222; border: 15px solid #222222; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
                                                    <span style="color:#ffffff;" class="button-link">&nbsp;&nbsp;&nbsp;&nbsp;A Button&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                </tr>
            </table>
        </td>
    </tr>
    <!-- Thumbnail Left, Text Right : END -->

    <!-- Thumbnail Right, Text Left : BEGIN -->
    <tr>
        <td bgcolor="#ffffff" dir="rtl" align="center" valign="top" width="100%" style="padding: 10px;">
            <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <!-- Column : BEGIN -->
                    <td width="33.33%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td dir="ltr" valign="top" style="padding: 0 10px;">
                                    <img src="http://placehold.it/170" aria-hidden="true" width="170" height="170" alt="alt_text" border="0" class="center-on-narrow" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                    <!-- Column : BEGIN -->
                    <td width="66.66%" class="stack-column-center">
                        <table role="presentation" aria-hidden="true" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td dir="ltr" valign="top" style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding: 10px; text-align: left;" class="center-on-narrow">
                                    <strong style="color:#111111;">Class aptent taciti sociosqu</strong>
                                    <br><br>
                                    Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                                    <br><br>
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" class="center-on-narrow" style="float:left;">
                                        <tr>
                                            <td style="border-radius: 3px; background: #222222; text-align: center;" class="button-td">
                                                <a href="http://www.google.com" style="background: #222222; border: 15px solid #222222; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
                                                    <span style="color:#ffffff;" class="button-link">&nbsp;&nbsp;&nbsp;&nbsp;A Button&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>
                        </table>
                    </td>
                    <!-- Column : END -->
                </tr>
            </table>
        </td>
    </tr>
    <!-- Thumbnail Right, Text Left : END -->

    <!-- Clear Spacer : BEGIN -->
    <tr>
        <td height="40" style="font-size: 0; line-height: 0;">
            &nbsp;
        </td>
    </tr>
    <!-- Clear Spacer : END -->

    <!-- 1 Column Text : BEGIN -->
    <tr>
        <td bgcolor="#ffffff">
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                    <td style="padding: 40px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                        Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent laoreet malesuada cursus. Maecenas scelerisque congue eros eu posuere. Praesent in felis ut velit pretium lobortis rhoncus ut&nbsp;erat.
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <!-- 1 Column Text : END -->

</table>
<!-- Email Body : END -->