<!-- Email Footer : BEGIN -->
<table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="600" style="margin: auto;" class="email-container">
    <tr>
        <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; line-height:18px; text-align: center; color: #888888;" class="x-gmail-data-detectors">
            <br><br>
            JiNexus Inc.<br>
            Cebu City, Cebu, 6000, Philippines<br>
            <?php echo $this->sampleFooterData . '<br>'; ?>
            <br><br>
        </td>
    </tr>
</table>
<!-- Email Footer : END -->