<!-- Visually Hidden Preheader Text : BEGIN -->
<div style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;">
    (Optional) This text will appear in the inbox preview, but not the email body. <?php echo $this->sampleHeaderData; ?>.
</div>
<!-- Visually Hidden Preheader Text : END -->

<!-- Email Header : BEGIN -->
<table role="presentation" aria-hidden="true" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="600" style="margin: auto;" class="email-container">
    <tr>
        <td style="padding: 20px 0; text-align: center">
            <img src="http://placehold.it/200x50" aria-hidden="true" width="200" height="50" alt="alt_text" border="0" style="height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
        </td>
    </tr>
</table>
<!-- Email Header : END -->